export const userData = [
  {
    id: 1,
    userName: "Sherill Damper",
    userpic: "/assets/person/1.jpeg",
  },
  {
    id: 2,
    userName: "Adair Schimaschke",
    userpic: "/assets/person/2.jpeg",
  },
  {
    id: 3,
    userName: "Kale Seden",
    userpic: "/assets/person/3.jpeg",
  },
  {
    id: 4,
    userName: "Catlin Hyett",
    userpic: "/assets/person/4.jpeg",
  },
  {
    id: 5,
    userName: "Wheeler Zarfai",
    userpic: "/assets/person/5.jpeg",
  },
  {
    id: 6,
    userName: "Rickie Biddles",
    userpic: "/assets/person/6.jpeg",
  },
  {
    id: 7,
    userName: "Jacenta Domerq",
    userpic: "/assets/person/7.jpeg",
  },
  {
    id: 8,
    userName: "Rhona Bruun",
    userpic: "/assets/person/8.jpeg",
  },
  {
    id: 9,
    userName: "Shell Howard",
    userpic: "/assets/person/9.jpeg",
  },
  {
    id: 10,
    userName: "Hetty Genese",
    userpic: "/assets/person/10.jpeg",
  },
  {
    id: 11,
    userName: "Paloma Prout",
    userpic: "/assets/person/1.jpeg",
  },
  {
    id: 12,
    userName: "Ransell Sheehy",
    userpic: "/assets/person/2.jpeg",
  },
  {
    id: 13,
    userName: "Mathew Atwood",
    userpic: "/assets/person/3.jpeg",
  },
  {
    id: 14,
    userName: "Aleen Carmody",
    userpic: "/assets/person/4.jpeg",
  },
  {
    id: 15,
    userName: "Wakefield Weld",
    userpic: "/assets/person/5.jpeg",
  },
  {
    id: 16,
    userName: "Tory Gori",
    userpic: "/assets/person/6.jpeg",
  },
  {
    id: 17,
    userName: "Chloe McAuley",
    userpic: "/assets/person/7.jpeg",
  },
  {
    id: 18,
    userName: "Maurita Devin",
    userpic: "/assets/person/8.jpeg",
  },
  {
    id: 19,
    userName: "Arlene Borthwick",
    userpic: "/assets/person/9.jpeg",
  },
  {
    id: 20,
    userName: "Isabel Champkin",
    userpic: "/assets/person/10.jpeg",
  },
];

export const postData = [
  {
    id: 1,
    post: "Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien.",
    photo: "/assets/post/1.jpeg",
    userId: 1,
    like: 1,
    comment: 1,
    date: "11:31 AM",
  },
  {
    id: 2,
    post: "In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum.",
    photo: "/assets/post/2.jpeg",
    userId: 2,
    like: 2,
    comment: 2,
    date: "10:23 PM",
  },
  {
    id: 3,
    post: "Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien.",
    photo: "/assets/post/3.jpeg",
    userId: 3,
    like: 3,
    comment: 3,
    date: "10:20 AM",
  },
  {
    id: 4,
    post: "In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.",
    photo: "/assets/post/4.jpeg",
    userId: 4,
    like: 4,
    comment: 4,
    date: "5:56 AM",
  },
  {
    id: 5,
    post: "Etiam justo. Etiam pretium iaculis justo.",
    photo: "/assets/post/5.jpeg",
    userId: 5,
    like: 5,
    comment: 5,
    date: "8:53 AM",
  },
  {
    id: 6,
    post: "Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh.",
    photo: "/assets/post/6.jpeg",
    userId: 6,
    like: 6,
    comment: 6,
    date: "7:12 PM",
  },
  {
    id: 7,
    post: "Aliquam non mauris. Morbi non lectus.",
    photo: "/assets/post/7.jpeg",
    userId: 7,
    like: 7,
    comment: 7,
    date: "3:09 AM",
  },
  {
    id: 8,
    post: "Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti.",
    photo: "/assets/post/8.jpeg",
    userId: 8,
    like: 8,
    comment: 8,
    date: "1:47 PM",
  },
  {
    id: 9,
    post: "Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.",
    photo: "/assets/post/9.jpeg",
    userId: 9,
    like: 9,
    comment: 9,
    date: "6:17 PM",
  },
  {
    id: 10,
    post: "In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis.",
    photo: "/assets/post/10.jpeg",
    userId: 10,
    like: 10,
    comment: 10,
    date: "5:52 AM",
  },
  {
    id: 11,
    post: "Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.",
    photo: "/assets/post/1.jpeg",
    userId: 11,
    like: 11,
    comment: 11,
    date: "7:25 AM",
  },
  {
    id: 12,
    post: "Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.",
    photo: "/assets/post/2.jpeg",
    userId: 12,
    like: 12,
    comment: 12,
    date: "3:05 AM",
  },
  {
    id: 13,
    post: "Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.",
    photo: "/assets/post/3.jpeg",
    userId: 13,
    like: 13,
    comment: 13,
    date: "4:36 PM",
  },
  {
    id: 14,
    post: "In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius.",
    photo: "/assets/post/4.jpeg",
    userId: 14,
    like: 14,
    comment: 14,
    date: "8:50 PM",
  },
  {
    id: 15,
    post: "Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
    photo: "/assets/post/5.jpeg",
    userId: 15,
    like: 15,
    comment: 15,
    date: "9:21 PM",
  },
  {
    id: 16,
    post: "Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.",
    photo: "/assets/post/6.jpeg",
    userId: 16,
    like: 16,
    comment: 16,
    date: "3:02 PM",
  },
  {
    id: 17,
    post: "Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.",
    photo: "/assets/post/7.jpeg",
    userId: 17,
    like: 17,
    comment: 17,
    date: "12:32 PM",
  },
  {
    id: 18,
    post: "Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.",
    photo: "/assets/post/8.jpeg",
    userId: 18,
    like: 18,
    comment: 18,
    date: "7:07 PM",
  },
  {
    id: 19,
    post: "In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum.",
    photo: "/assets/post/9.jpeg",
    userId: 19,
    like: 19,
    comment: 19,
    date: "7:02 AM",
  },
  {
    id: 20,
    post: "Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit.",
    photo: "/assets/post/10.jpeg",
    userId: 20,
    like: 20,
    comment: 20,
    date: "4:08 AM",
  },
];
